name = "Aurona"
author = "Chasin"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "932a7e46aaeee57a15ff367c13dc2bfbebd171e6ccc70fa1aea4ea99d1735677"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
