name = "Aurona"
author = "Chasin"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ac7cb00ae8438c5e19414d9bde16a4936fd3b0773c927de6aa3cd552a583d77"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
